# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    volumes:
      - c:/dev/data:/var/lib/mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: spring_social

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080